name: build

on:
  push:
    tags: ['v*']
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish
        run: >
          dotnet publish src/Wallshall/Wallshall.csproj -c Release -r win-x64
          -p:EnableWindowsTargeting=true -p:PublishSingleFile=true
          --self-contained false -o dist

      - name: Publish standalone
        run: >
          dotnet publish src/Wallshall/Wallshall.csproj -c Release -r win-x64
          -p:EnableWindowsTargeting=true -p:PublishSingleFile=true
          -p:IncludeNativeLibrariesForSelfExtract=true
          --self-contained true -o dist-standalone

      - name: Collect
        run: |
          mv dist-standalone/Wallshall.exe dist/Wallshall-standalone.exe
          ls -l dist

      - uses: actions/upload-artifact@v4
        with:
          name: Wallshall
          path: |
            dist/Wallshall.exe
            dist/Wallshall-standalone.exe

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/Wallshall.exe
            dist/Wallshall-standalone.exe